import js from '@eslint/js'
import { defineConfig, globalIgnores } from 'eslint/config'
import globals from 'globals'
import tseslint from 'typescript-eslint'

const unusedVars = [
  'error',
  { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
]

export default defineConfig([
  globalIgnores([
    'dist',
    'node_modules',
    'public/data',
    'test-results',
    'playwright-report',
    'coverage',
    '.wrangler',
    // Generated by `wrangler types`; checked by worker/tsconfig.json.
    'worker-configuration.d.ts',
  ]),
  {
    files: ['**/*.ts'],
    // Type-aware rules read the tsconfig project, so they catch what syntax
    // alone cannot: a promise that nothing waits on, an any that leaks.
    extends: [js.configs.recommended, tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': unusedVars,
    },
  },
  {
    files: ['*.config.ts'],
    languageOptions: { globals: globals.node },
  },
  // The Worker and its tests run in workerd, not a browser.
  {
    files: ['worker/**/*.ts', 'tests/worker/**/*.ts'],
    languageOptions: { globals: globals.serviceworker },
  },
  // The config files and the geo fetch script stay plain JS.
  {
    files: ['**/*.{js,cjs}'],
    extends: [js.configs.recommended],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.node,
    },
    rules: {
      'no-unused-vars': unusedVars,
    },
  },
])
