// The DOM helpers every panel and dialog shares: an element with a class
// and text, a required node under a root, and a status line with its tone.
// Markup is generated by each module, so a node it cannot find is a bug
// there, and these throw.

// An element with `className` and, when given, `content` as text: a key
// label like "< >" is not markup.
export function el<K extends keyof HTMLElementTagNameMap>(
  tag: K,
  className?: string,
  content?: string
): HTMLElementTagNameMap[K] {
  const node = document.createElement(tag)
  if (className) node.className = className
  if (content !== undefined) node.textContent = content
  return node
}

// An element holding `content` as text, the class after it.
export function text<K extends keyof HTMLElementTagNameMap>(
  tag: K,
  content: string,
  className?: string
): HTMLElementTagNameMap[K] {
  return el(tag, className, content)
}

// The one node `selector` names under `root`.
export function find<T extends Element>(root: ParentNode, selector: string): T {
  const found = root.querySelector<T>(selector)
  if (!found) throw new Error(`Missing ${selector}`)
  return found
}

// A finder bound to `root`: a dialog names its nodes with one.
export function finder(
  root: ParentNode
): <T extends Element>(selector: string, from?: ParentNode) => T {
  return <T extends Element>(selector: string, from: ParentNode = root) =>
    find<T>(from, selector)
}

// A status line's tone: styles.css colors [data-tone].
export type Tone = 'ok' | 'bad' | null

// A status line's text and tone, none for a plain line.
export function setStatus(
  status: HTMLElement,
  text: string,
  tone: Tone = null
): void {
  status.textContent = text
  if (tone) status.dataset.tone = tone
  else delete status.dataset.tone
}
